name: Pathways Education Support
favicon: null
layout_spectrum: 0.09069306124001741
typography_spectrum: 0.20913448184728622
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.489277645945549
  lightness: 0.6510155010037124
  saturation: 0.6822203195188195
  rhythmicContrast: 0.33886169036850333
purpose: []
